services:
  # A Node web service
  - type: web
    name: render-example-puppeteer
    runtime: node
    region: oregon
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/puppeteer
  - type: cron
    name: render-example-puppeteer-cron
    runtime: node
    schedule: "0 0 * * *"
    region: oregon
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: node cron.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/puppeteer